import { defineConfig, Plugin } from 'vite';
import { svelte } from '@sveltejs/vite-plugin-svelte';
import { resolve } from 'path';
import { createHash } from 'crypto';
import { readdirSync, statSync, existsSync } from 'fs';
import { join } from 'path';
import type { OutputBundle } from 'rollup';

function serviceWorkerManifest(): Plugin {
  const virtualModuleId = 'virtual:sw-manifest';
  const resolvedVirtualModuleId = '\0' + virtualModuleId;

  return {
    name: 'sw-manifest',
    resolveId(id) {
      if (id === virtualModuleId) {
        return resolvedVirtualModuleId;
      }
    },
    load(id) {
      if (id === resolvedVirtualModuleId) {
        // Return placeholder that will be replaced in generateBundle
        return `export const CACHE_VERSION = '__CACHE_VERSION__'; export const STATIC_ASSETS = '__STATIC_ASSETS__';`;
      }
    },
    generateBundle(_options, bundle: OutputBundle) {
      // Collect all files from the bundle (JS, CSS)
      const allFiles = new Set<string>();
      for (const fileName of Object.keys(bundle)) {
        allFiles.add('/' + fileName);
      }

      // Add static files from public directory
      const publicDir = 'public';
      if (existsSync(publicDir)) {
        const publicFiles = readdirSync(publicDir);
        for (const file of publicFiles) {
          const fullPath = join(publicDir, file);
          if (statSync(fullPath).isFile()) {
            allFiles.add('/' + file);
          }
        }
      }

      // Add index.html (generated by Vite but not in bundle)
      allFiles.add('/index.html');
      allFiles.add('/'); // Root path

      // Find the service worker chunk
      const swChunk = Object.values(bundle).find(
        chunk => chunk.type === 'chunk' && chunk.fileName === 'service-worker.js'
      );

      if (swChunk && swChunk.type === 'chunk') {
        const fileList = Array.from(allFiles).sort();

        const hash = createHash('sha256');
        hash.update(fileList.join('\n'));
        const cacheVersion = hash.digest('hex').substring(0, 8);

        // Replace placeholders in the service worker code
        swChunk.code = swChunk.code
          .replace('"__CACHE_VERSION__"', JSON.stringify(cacheVersion))
          .replace('"__STATIC_ASSETS__"', JSON.stringify(fileList));

        console.log(`Service worker manifest: ${fileList.length} files, version: ${cacheVersion}`);
      }
    }
  };
}

export default defineConfig({
  plugins: [svelte(), serviceWorkerManifest()],
  base: '/',
  resolve: {
    alias: {
      $lib: resolve(__dirname, './src/lib'),
    },
  },
  build: {
    outDir: 'site',
    emptyOutDir: true,
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        sw: resolve(__dirname, 'src/service-worker.ts'),
      },
      output: {
        entryFileNames: (chunkInfo) => {
          if (chunkInfo.name === 'sw') {
            return 'service-worker.js';
          }
          return 'assets/[name]-[hash].js';
        },
      },
    },
  },
});
